### ISSUE TITLE
[Bug]: `CurpGroup` related tests panic

### ISSUE THREAD

**Issue by themanforfree** [xline-kv/Xline#376]
### Description about the bug

`basic_propose`, `concurrent_cmd_order`, etc. the tests  that depends in `CurpGroup` maybe panic.

### Version

0.4.1 (Default)

### Relevant log output

```shell
...
`concurrent_cmd_order` panic! 
@info:
panicked at 'failed to send exe msg: SendError((TestCommand { id: ProposeId("1"), keys: [0], exe_dur: 1s, as_dur: 0ns, exe_should_fail: false, as_should_fail: false, cmd_type: Put(0) }, ([], [])))', curp-test-utils/src/test_cmd.rs:234:14
@stackTrace:
   0: server::concurrent_cmd_order::{{closure}}
             at ./tests/server.rs:147:1
   1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/alloc/src/boxed.rs:1987:9
   2: std::panicking::rust_panic_with_hook
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:695:13
   3: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:582:13
...
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Phoenix500526** [comment]
So, what's the root cause of this issue?
