### ISSUE TITLE
[Bug]: Restore a leader might cause two leader at the same time

### ISSUE THREAD

**Issue by iGxnon** [xline-kv/Xline#457]
### Description about the bug

Restore a leader might cause two leader at the same time

IT `leader_and_follower_both_crash_and_recovery` failed sometimes because we rapidly crash and restore the leader

```rust
group.crash(leader).await;

// It might elect a new leader here.

// restart the original leader
group.restart(leader, false).await;
```

Because the original leader will retain the `is_leader` flag, it will directly become the leader.

```rust
if is_leader {
    let mut st_w = raw_curp.st.write();
    raw_curp.become_leader(&mut st_w);
}
```

Thus, we got two leaders at the same time. The node that considers itself a leader is not the actual leader, but it can still attempt to execute commands proposed by the clients before receiving the AE of the actual leader.

Finally, client will crash because it sets ER twice.

```rust
if let Some(er) = res
    .transpose()
    .map_err(|e| CommandProposeError::Execute(e))?
{
    assert!(execute_result.is_none(), "should not set exe result twice");
    execute_result = Some(er);
}
```

### Version

0.4.1 (Default)

### Relevant log output

```shell
23.789006512s DEBUG curp::server::raw_curp: Follower 2720582221265193317 starts election
  23.789006512s DEBUG curp::server::raw_curp: 2720582221265193317's vote is granted by server 2720582221265193317
  23.789006512s DEBUG curp::server::curp_node: 2720582221265193317 broadcasts votes to all servers
  23.789007562s  WARN curp::server::curp_node: request vote from 11778213386565707572 failed, rcp error status: Unavailable, message: "transport error", details: [], metadata: MetadataMap { headers: {} }
  23.789011612s  WARN curp::server::curp_node: request vote from 16802816270467148322 failed, rcp error status: Unavailable, message: "transport error", details: [], metadata: MetadataMap { headers: {} }
  23.790146633s DEBUG curp_vote: curp::server::raw_curp: 10969678924883983225 received vote: term(1), last_log_index(2), last_log_term(0), id(2720582221265193317)
  23.790146633s DEBUG curp_vote: curp::server::raw_curp: 10969678924883983225 updates to term 1 and becomes a follower
  23.790146633s DEBUG curp_vote: curp::server::raw_curp: 10969678924883983225 votes for server 2720582221265193317
  23.793973858s DEBUG curp_vote: curp::server::raw_curp: 12573301193243005289 received vote: term(1), last_log_index(2), last_log_term(0), id(2720582221265193317)
  23.793973858s DEBUG curp_vote: curp::server::raw_curp: 12573301193243005289 updates to term 1 and becomes a follower
  23.793973858s DEBUG curp_vote: curp::server::raw_curp: 12573301193243005289 votes for server 2720582221265193317
  23.794180979s DEBUG curp::server::raw_curp: 2720582221265193317's vote is granted by server 10969678924883983225
  23.800332138s DEBUG curp::server::raw_curp: 2720582221265193317's vote is granted by server 12573301193243005289
  23.800332138s DEBUG curp::server::raw_curp: 2720582221265193317 collected spec pools: {10969678924883983225: "", 12573301193243005289: "", 2720582221265193317: ""}
  23.800332138s DEBUG curp::server::raw_curp: 2720582221265193317 becomes the leader
  23.800332194s DEBUG curp::server::curp_node: 2720582221265193317 send ae to 10969678924883983225
  23.800332194s DEBUG curp::server::curp_node: 2720582221265193317 send ae to 11778213386565707572
  23.800332194s DEBUG curp::server::curp_node: 2720582221265193317 send ae to 12573301193243005289
  23.800332194s DEBUG curp::server::curp_node: 2720582221265193317 send ae to 16802816270467148322
  23.800335244s  WARN curp::server::curp_node: ae to 11778213386565707572 failed, transport error, rcp error status: Unavailable, message: "transport error", details: [], metadata: MetadataMap { headers: {} }
  23.800335244s  WARN curp::server::curp_node: ae to 16802816270467148322 failed, transport error, rcp error status: Unavailable, message: "transport error", details: [], metadata: MetadataMap { headers: {} }
  23.806117401s DEBUG curp_append_entries: curp::server::raw_curp: 10969678924883983225 received append_entries from 2720582221265193317: term(1), commit(1), prev_log_index(2), prev_log_term(0), 0 entries
  23.807274785s DEBUG curp_append_entries: curp::server::raw_curp: 12573301193243005289 received append_entries from 2720582221265193317: term(1), commit(1), prev_log_index(2), prev_log_term(0), 0 entries
  24.100332244s DEBUG curp::server::curp_node: 2720582221265193317 send ae to 10969678924883983225
  24.100332244s DEBUG curp::server::curp_node: 2720582221265193317 send ae to 11778213386565707572
  24.100332244s DEBUG curp::server::curp_node: 2720582221265193317 send ae to 12573301193243005289
  24.100332244s DEBUG curp::server::curp_node: 2720582221265193317 send ae to 16802816270467148322
  24.100334294s  WARN curp::server::curp_node: ae to 11778213386565707572 failed, transport error, rcp error status: Unavailable, message: "transport error", details: [], metadata: MetadataMap { headers: {} }
  24.100336244s  WARN curp::server::curp_node: ae to 16802816270467148322 failed, transport error, rcp error status: Unavailable, message: "transport error", details: [], metadata: MetadataMap { headers: {} }
  24.101689410s DEBUG curp_append_entries: curp::server::raw_curp: 12573301193243005289 received append_entries from 2720582221265193317: term(1), commit(1), prev_log_index(2), prev_log_term(0), 0 entries
  24.107857400s  INFO curp::server::curp_node: 16802816270467148322 recovered voted_for(None), entries from Some(LogEntry { term: 0, index: 1, entry_data: Command(TestCommand { id: "1", keys: [0], exe_dur: 0ns, as_dur: 0ns, exe_should_fail: false, as_should_fail: false, cmd_type: Put(0) }) }) to Some(LogEntry { term: 0, index: 2, entry_data: Command(TestCommand { id: "2", keys: [0], exe_dur: 0ns, as_dur: 0ns, exe_should_fail: false, as_should_fail: false, cmd_type: Get }) })
  24.107857400s DEBUG curp::server::raw_curp: 16802816270467148322 becomes the leader
  24.107858294s DEBUG propose:fast_round: curp::client: fast round for cmd(3) started cmd_id=3
  24.107858294s DEBUG propose:slow_round: curp::client: slow round for cmd(3) started cmd_id=3
  24.107858294s DEBUG propose:slow_round: curp::client: wait synced request sent to 16802816270467148322 cmd_id=3
  24.107858376s DEBUG curp::server::curp_node: 16802816270467148322 send ae to 12573301193243005289
  24.107858376s DEBUG curp::server::curp_node: 16802816270467148322 send ae to 10969678924883983225
  24.107858376s DEBUG curp::server::curp_node: 16802816270467148322 send ae to 2720582221265193317
  24.107858376s DEBUG curp::server::curp_node: 16802816270467148322 send ae to 11778213386565707572
  24.107863394s  WARN propose:fast_round: curp::client: Propose error: rcp error status: Unavailable, message: "transport error", details: [], metadata: MetadataMap { headers: {} } cmd_id=3
  24.107865444s  WARN curp::server::curp_node: ae to 11778213386565707572 failed, transport error, rcp error status: Unavailable, message: "transport error", details: [], metadata: MetadataMap { headers: {} }
  24.109732048s DEBUG curp_append_entries: curp::server::raw_curp: 10969678924883983225 received append_entries from 2720582221265193317: term(1), commit(1), prev_log_index(2), prev_log_term(0), 0 entries
  24.110479641s DEBUG curp_append_entries: curp::server::raw_curp: 2720582221265193317 received append_entries from 16802816270467148322: term(0), commit(1), prev_log_index(0), prev_log_term(0), 2 entries
  24.112763539s DEBUG curp_propose: curp::server::raw_curp: 12573301193243005289 gets proposal for cmd(3)
  24.112763539s DEBUG curp_propose: curp::server::spec_pool: insert cmd(3) into spec pool
  24.112922898s DEBUG curp_append_entries: curp::server::raw_curp: 12573301193243005289 received append_entries from 16802816270467148322: term(0), commit(1), prev_log_index(0), prev_log_term(0), 2 entries
  24.113465986s DEBUG curp_propose: curp::server::raw_curp: 10969678924883983225 gets proposal for cmd(3)
  24.113465986s DEBUG curp_propose: curp::server::spec_pool: insert cmd(3) into spec pool
  24.113470082s DEBUG curp_append_entries: curp::server::raw_curp: 10969678924883983225 received append_entries from 16802816270467148322: term(0), commit(1), prev_log_index(0), prev_log_term(0), 2 entries
  24.115100228s DEBUG curp_wait_synced: curp::server::curp_node: 16802816270467148322 get wait synced request for cmd(3)
  24.115769916s DEBUG curp_propose: curp::server::raw_curp: 2720582221265193317 gets proposal for cmd(3)
  24.115769916s DEBUG curp_propose: curp::server::spec_pool: insert cmd(3) into spec pool
  24.115769916s DEBUG curp_propose: curp::server::raw_curp: 2720582221265193317 gets new log[3]
  24.115770063s DEBUG curp::server::cmd_worker::conflict_checked_mpmc: new ce event: SpecExeReady(LogEntry { term: 1, index: 3, entry_data: Command(TestCommand { id: "3", keys: [0], exe_dur: 0ns, as_dur: 0ns, exe_should_fail: false, as_should_fail: false, cmd_type: Get }) })
  24.115770130s DEBUG curp_test_utils::test_cmd: S3 execute cmd(3)
  24.115770130s DEBUG curp::server::cmd_worker: 2720582221265193317 cmd(3) is speculatively executed, exe status: true
  24.116369925s DEBUG curp_propose: curp::server::raw_curp: 16802816270467148322 gets proposal for cmd(3)
  24.116369925s DEBUG curp_propose: curp::server::spec_pool: insert cmd(3) into spec pool
  24.116369925s DEBUG curp_propose: curp::server::raw_curp: 16802816270467148322 gets new log[3]
  24.116370008s DEBUG curp::server::cmd_worker::conflict_checked_mpmc: new ce event: SpecExeReady(LogEntry { term: 0, index: 3, entry_data: Command(TestCommand { id: "3", keys: [0], exe_dur: 0ns, as_dur: 0ns, exe_should_fail: false, as_should_fail: false, cmd_type: Get }) })
  24.116370059s DEBUG curp_test_utils::test_cmd: S0 execute cmd(3)
  24.116370059s DEBUG curp::server::cmd_worker: 16802816270467148322 cmd(3) is speculatively executed, exe status: true
  24.116428432s DEBUG propose:fast_round: curp::client: client update its leader to 2720582221265193317 cmd_id=3
  24.118172904s DEBUG curp::server::raw_curp: leader 16802816270467148322 retires
  24.118172904s DEBUG curp::server::raw_curp: 16802816270467148322 updates to term 1 and becomes a follower
  24.118172904s  WARN curp::server::curp_node: ae to 2720582221265193317 failed, self is no longer leader
  24.118786515s  WARN curp::server::curp_node: ae to 12573301193243005289 failed, self is no longer leader
  24.119586810s  WARN curp::server::curp_node: ae to 10969678924883983225 failed, self is no longer leader
  24.121511063s DEBUG curp::server::curp_node: 2720582221265193317 send ae to 12573301193243005289

should not set exe result twice
thread '<unnamed>' panicked at 'should not set exe result twice', /Users/igxnon/workspace/rust/Xline/curp/src/client.rs:277:25
stack backtrace:
   0: rust_begin_unwind
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:578:5
   1: core::panicking::panic_fmt
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:67:14
   2: curp::client::Client<C>::fast_round::{{closure}}::{{closure}}::{{closure}}
             at /Users/igxnon/workspace/rust/Xline/curp/src/client.rs:277:25
   3: curp::rpc::<impl curp::rpc::proto::commandpb::ProposeResponse>::map_or_else
             at /Users/igxnon/workspace/rust/Xline/curp/src/rpc/mod.rs:211:20
   4: curp::client::Client<C>::fast_round::{{closure}}::{{closure}}
             at /Users/igxnon/workspace/rust/Xline/curp/src/client.rs:271:13
   5: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at /Users/igxnon/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
   6: curp::client::Client<C>::fast_round::{{closure}}
             at /Users/igxnon/workspace/rust/Xline/curp/src/client.rs:236:5
   7: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/future/future.rs:125:9
   8: futures_util::future::future::FutureExt::poll_unpin
             at /Users/igxnon/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/future/future/mod.rs:562:9
   9: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
             at /Users/igxnon/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/future/select.rs:114:35
  10: curp::client::Client<C>::propose::{{closure}}::{{closure}}
             at /Users/igxnon/workspace/rust/Xline/curp/src/client.rs:613:66
  11: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at /Users/igxnon/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  12: curp::client::Client<C>::propose::{{closure}}
             at /Users/igxnon/workspace/rust/Xline/curp/src/client.rs:598:5
  13: simulation::curp_group::SimClient<C>::propose::{{closure}}::{{closure}}
             at ./src/curp_group.rs:365:66
  14: madsim::sim::task::Spawner::spawn_inner::{{closure}}::{{closure}}
             at /Users/igxnon/.cargo/git/checkouts/madsim-e41dc49cac5b4fae/5eb4198/madsim/src/sim/task/mod.rs:629:27
  15: <async_task::runnable::Builder<M>::spawn_local::Checked<F> as core::future::future::Future>::poll
             at /Users/igxnon/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-task-4.4.0/src/runnable.rs:455:26
  16: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/future/future.rs:125:9
  17: async_task::raw::RawTask<F,T,S,M>::run
             at /Users/igxnon/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-task-4.4.0/src/raw.rs:563:17
  18: async_task::runnable::Runnable<M>::run
             at /Users/igxnon/.cargo/registry/src/index.crates.io-6f17d22bba15001f/async-task-4.4.0/src/runnable.rs:782:18
  19: madsim::sim::task::Executor::run_all_ready::{{closure}}
             at /Users/igxnon/.cargo/git/checkouts/madsim-e41dc49cac5b4fae/5eb4198/madsim/src/sim/task/mod.rs:271:50
  20: std::panicking::try::do_call
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:485:40
  21: ___rust_try
  22: std::panicking::try
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:449:19
  23: std::panic::catch_unwind
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panic.rs:140:14
  24: madsim::sim::task::Executor::run_all_ready
             at /Users/igxnon/.cargo/git/checkouts/madsim-e41dc49cac5b4fae/5eb4198/madsim/src/sim/task/mod.rs:271:17
  25: madsim::sim::task::Executor::block_on
             at /Users/igxnon/.cargo/git/checkouts/madsim-e41dc49cac5b4fae/5eb4198/madsim/src/sim/task/mod.rs:238:13
  26: madsim::sim::runtime::Runtime::block_on
             at /Users/igxnon/.cargo/git/checkouts/madsim-e41dc49cac5b4fae/5eb4198/madsim/src/sim/runtime/mod.rs:126:9
  27: madsim::sim::runtime::builder::Builder::run::{{closure}}::{{closure}}::{{closure}}
             at /Users/igxnon/.cargo/git/checkouts/madsim-e41dc49cac5b4fae/5eb4198/madsim/src/sim/runtime/builder.rs:128:35
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
context: node=6 "client", task=399 (spawned at /Users/igxnon/workspace/rust/Xline/simulation/src/curp_group.rs:365:14)
note: run with `MADSIM_TEST_SEED=1695466730908956000` environment variable to reproduce this error

error: test failed, to rerun pass `--test it`
error: 1 target failed:
    `--test it`
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by iGxnon** [comment]
Why do we need to add the `is_leader` flag when starting the node? Besides being able to skip the first election timeout, does it serve any other purpose?

**Comment by iGxnon** [comment]
In the case of the user setting is_leader reasonably, for example, when restarting the leader node, is_leader cannot be set.
So we can retain is_leader.
