### ISSUE TITLE
[Bug]:  ```test_range_redirect``` related tests panic

### ISSUE THREAD

**Issue by Kikkon** [xline-kv/Xline#519]
### Description about the bug

#496 it was discovered that the relevant tests for test_range_redirect would panic. It seems unrelated to the submission in #

### Version

0.4.1 (Default)

### Relevant log output

```shell
`test_range_redirect` panic! 
@info:
panicked at 'failed to create curp service, storage error, internal error, I/O Error:  No such file or directory: While renaming a file to /tmp/xline-YZQ0gq24/curp/CURRENT: /tmp/xline-YZQ0gq24/curp/000005.dbtmp: No such file or directory', /home/runner/work/Xline/Xline/curp/src/server/mod.rs:198:17
@stackTrace:
   0: kv_test::test_range_redirect::{{closure}}
             at ./tests/kv_test.rs:165:1
   1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/alloc/src/boxed.rs:1987:9
   2: std::panicking::rust_panic_with_hook
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:695:13
   3: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:582:13
   4: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:150:18
   5: rust_begin_unwind
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:578:5
   6: core::panicking::panic_fmt
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:67:14
   7: curp::server::Rpc<C,RC>::new::{{closure}}
  ........
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Phoenix500526** [comment]
Closed since it's duplicated with issue #406
