### ISSUE TITLE
[Bug]: xline-client build fails with File Not Found error on protoc files

### ISSUE THREAD

**Issue by koolquark** [xline-kv/Xline#564]
### Description about the bug

xline-client build fails complaining that protoc files are missing 

** xline client version ** 
`master`
**commit :** 
`e831834235e992614bb536a639763646ddeee565`

**Protoc**
```
protoc --version
libprotoc 25.1`

```
**Cargo.toml** 

```
[package]
name = "example_client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xline-client = { git = "https://github.com/xline-kv/Xline.git", package = "xline-client", branch="master"}
```

**Compiler output** 

```
CARGO_TARGET_DIR=t cargo run
   Compiling librocksdb-sys v0.11.0+8.1.1
   Compiling curp v0.1.0 (https://github.com/xline-kv/Xline.git?branch=master#e8318342)
   Compiling xlineapi v0.1.0 (https://github.com/xline-kv/Xline.git?branch=master#e8318342)
   Compiling madsim-etcd-client v0.3.0+0.11.1
error: failed to run custom build command for `curp v0.1.0 (https://github.com/xline-kv/Xline.git?branch=master#e8318342)`

Caused by:
  process didn't exit successfully: `/home/anz/w/compass_ng/cngsa/example_client/t/debug/build/curp-145ee5a43796ec61/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at /home/anz/.cargo/git/checkouts/xline-2dbca1bd90817c39/e831834/curp/build.rs:11:29:
  Failed to compile proto, error is Custom { kind: Other, error: "protoc failed: google/protobuf/empty.proto: File not found.\ncurp-command.proto:6:1: Import \"google/protobuf/empty.proto\" was not found or had errors.\ncurp-command.proto:124:9: \"google.protobuf.Empty\" is not defined.\ncurp-command.proto:125:9: \"google.protobuf.Empty\" is not defined.\ncurp-command.proto:126:9: \"google.protobuf.Empty\" is not defined.\ncurp-command.proto:127:9: \"google.protobuf.Empty\" is not defined.\n" }
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: failed to run custom build command for `xlineapi v0.1.0 (https://github.com/xline-kv/Xline.git?branch=master#e8318342)`

Caused by:
  process didn't exit successfully: `/home/anz/w/compass_ng/cngsa/example_client/t/debug/build/xlineapi-d7a9265406ddebfc/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at /home/anz/.cargo/git/checkouts/xline-2dbca1bd90817c39/e831834/xlineapi/build.rs:16:29:
  Failed to compile proto, error is Custom { kind: Other, error: "protoc failed: google/protobuf/empty.proto: File not found.\nxline-error.proto:5:1: Import \"google/protobuf/empty.proto\" was not found or had errors.\nxline-error.proto:12:9: \"google.protobuf.Empty\" is not defined.\nxline-error.proto:19:9: \"google.protobuf.Empty\" is not defined.\nxline-error.proto:20:9: \"google.protobuf.Empty\" is not defined.\nxline-error.proto:24:9: \"google.protobuf.Empty\" is not defined.\nxline-error.proto:28:9: \"google.protobuf.Empty\" is not defined.\nxline-error.proto:29:9: \"google.protobuf.Empty\" is not defined.\nxline-error.proto:30:9: \"google.protobuf.Empty\" is not defined.\nxline-error.proto:31:9: \"google.protobuf.Empty\" is not defined.\nxline-error.proto:32:9: \"google.protobuf.Empty\" is not defined.\nxline-error.proto:33:9: \"google.protobuf.Empty\" is not defined.\nxline-error.proto:34:9: \"google.protobuf.Empty\" is not defined.\nxline-error.proto:37:9: \"google.protobuf.Empty\" is not defined.\n" }
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
Any help is appreciated

### Version

0.6.0 (Default)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by koolquark** [comment]
Rustc version : rustc 1.70.0 (90c541806 2023-05-31)

**Comment by koolquark** [comment]
The issue is resolved after installing the required dependency `protobuf-compiler >= 3.15`  as mentioned in [QuickStart](https://github.com/xline-kv/Xline/blob/master/doc/quick-start/README.md)
