### ISSUE TITLE
[Bug]:  Can not restore data from snapshot

### ISSUE THREAD

**Issue by liangyuanpeng** [xline-kv/Xline#607]
### Description about the bug

Can not restore the snapshot from etcd  snapshot of xline.

Reproduce it:

1. start xline
2. etcdctl put /hello world
3. etcdctl  snapshot save test.db 
4. etcdctl snapshot restore test.db --data-dir /tmp/xline

I can see the script to validation the  snapshot save, and have not validation  the snapshot restore, Is this the design goal of xline?

https://github.com/xline-kv/Xline/blob/6ebc04ad18e79142ab5ea9f5505e59ff1955d9bd/scripts/validation_test.sh#L222-L228

### Version

0.6.0 (Default)

### Relevant log output

```shell
Deprecated: Use `etcdutl snapshot restore` instead.

2024-01-10T10:26:09Z    info    snapshot/v3_snapshot.go:260     restoring snapshot      {"path": "test.db", "wal-dir": "/tmp/xline/member/wal", "data-dir": "/tmp/xline", "snap-dir": "/tmp/xline/member/snap"}
panic: failed to open database

goroutine 1 [running]:
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc00015a180, {0xc0000aa080, 0x2, 0x2})
        go.uber.org/zap@v1.17.0/zapcore/entry.go:234 +0x49b
go.uber.org/zap.(*Logger).Panic(0xc000040560?, {0xded412?, 0x1523b80?}, {0xc0000aa080, 0x2, 0x2})
        go.uber.org/zap@v1.17.0/logger.go:227 +0x59
go.etcd.io/etcd/server/v3/mvcc/backend.newBackend({{0xc000040560, 0x19}, 0x5f5e100, 0x2710, {0x0, 0x0}, 0x280000000, 0xc000090050, 0x0, 0x0, ...})
        go.etcd.io/etcd/server/v3@v3.5.11/mvcc/backend/backend.go:189 +0x429
go.etcd.io/etcd/server/v3/mvcc/backend.NewDefaultBackend(...)
        go.etcd.io/etcd/server/v3@v3.5.11/mvcc/backend/backend.go:169
go.etcd.io/etcd/etcdutl/v3/snapshot.(*v3Manager).saveDB(0xc000577ba0)
        go.etcd.io/etcd/etcdutl/v3@v3.5.11/snapshot/v3_snapshot.go:313 +0x158
go.etcd.io/etcd/etcdutl/v3/snapshot.(*v3Manager).Restore(0xc000577ba0, {{0x7ffff1e28dc6, 0x7}, {0xdde41f, 0x7}, {0x7ffff1e28dd9, 0xa}, {0xc0003ac240, 0x15}, {0xc00011d4a0, ...}, ...})
        go.etcd.io/etcd/etcdutl/v3@v3.5.11/snapshot/v3_snapshot.go:268 +0x7c8
go.etcd.io/etcd/etcdutl/v3/etcdutl.SnapshotRestoreCommandFunc({0xc000398260, 0x1d}, {0xde315f, 0xc}, {0x7ffff1e28dd9, 0xa}, {0x0, 0x0}, {0xdeb58f, 0x15}, ...)
        go.etcd.io/etcd/etcdutl/v3@v3.5.11/etcdutl/snapshot_command.go:158 +0x465
go.etcd.io/etcd/etcdctl/v3/ctlv3/command.snapshotRestoreCommandFunc(0xc00048a280?, {0xc000492210, 0x1, 0x3})
        go.etcd.io/etcd/etcdctl/v3/ctlv3/command/snapshot_command.go:133 +0x13d
github.com/spf13/cobra.(*Command).execute(0xc00048a280, {0xc0004921e0, 0x3, 0x3})
        github.com/spf13/cobra@v1.1.3/command.go:856 +0x663
github.com/spf13/cobra.(*Command).ExecuteC(0x14e1c60)
        github.com/spf13/cobra@v1.1.3/command.go:960 +0x39d
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.1.3/command.go:897
go.etcd.io/etcd/etcdctl/v3/ctlv3.Start()
        go.etcd.io/etcd/etcdctl/v3/ctlv3/ctl.go:107 +0x97
go.etcd.io/etcd/etcdctl/v3/ctlv3.MustStart()
        go.etcd.io/etcd/etcdctl/v3/ctlv3/ctl.go:111 +0x19
main.main()
        go.etcd.io/etcd/etcdctl/v3/main.go:59 +0x65
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by liangyuanpeng** [comment]
I have see the PR https://github.com/xline-kv/Xline/pull/244 is working for snapshot restore, and not sure is this the same as etcdctl snapshot restore.

**Comment by liangyuanpeng** [comment]
please free feel to close it if it's not the goal of xline.
